spring.application.name=imaging-mvp
server.port=8080

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/imagingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

app.storage.root=uploads
